//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMONIC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyResponses
    {
        public int ID { get; set; }
        public System.DateTime SurveyMonth { get; set; }
        public Nullable<int> DepartureAirportID { get; set; }
        public Nullable<int> ArrivalAirportID { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<int> CabinTypeID { get; set; }
        public byte Q1 { get; set; }
        public byte Q2 { get; set; }
        public byte Q3 { get; set; }
        public byte Q4 { get; set; }
    
        public virtual Airports Airports { get; set; }
        public virtual CabinTypes CabinTypes { get; set; }
    }
}
